- name: install k3s master
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ install_k3s_version }}" sh -s - \
    --write-kubeconfig-mode 644 \
    --node-name {{ master_first_name }} \
    --cluster-cidr {{ cluster_cidr }} \
    --cluster-init \
    --service-cidr {{ service_cidr }} \
    --cluster-dns {{ cluster_dns }} \
    --tls-san {{ master_first_ip_public }} \
    --token {{ k3s_cluster_secret }} \
    --prefer-bundled-bin
  args:
    executable: /bin/bash

- name: Fetch kubeconfig from master
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.k3s/config
    flat: yes