apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-assistant
  name: home-assistant
  namespace: domotica
spec:
  ports:
    - name: "8123"
      port: 8123
      protocol: TCP
      targetPort: 8123
  selector:
    app: home-assistant
  sessionAffinity: None
  type: ClusterIP