apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-nfs-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi  # Asegúrate de que esto coincida con lo que especificaste en el PV
  storageClassName: nfs
  selector:
    matchLabels:
      type: nfs
